name: Build and Deploy Hugo Site

on:
  workflow_dispatch:
    inputs:
      google_region:
        description: 'GCP Region to deploy the Cloud Run app to'
        required: true
        type: string
      google_artifact_registry:
        description: 'The Google Artifact Registry instance to upload the image to'
        required: true
        type: string
      image_name:
        description: 'The name of the docker image to upload'
        required: true
        type: string
      image_tag:
        description: 'The tag of the docker image to upload'
        required: true
        type: string
      cloud_run_service_account:
        description: 'The service account used by the cloud run instance'
        required: true
        type: string
      max_instances:
        description: 'The maximum number of cloud run instances to run in this service'
        required: false
        type: string
        default: "3"
      workload_identity_provider:
        description: 'The workload identity provider pool'
        required: true
        type: string
      workload_identity_service_account:
        description: 'The service account used by GitHub actions'
        required: true
        type: string
    secrets:
      github_token:
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      pull-requests: 'read'
      id-token: 'write'
    env:
      GITHUB_TOKEN: ${{ secrets.github_token }}
      GOOGLE_REGION: ${{ inputs.google_region }}
      GOOGLE_ARTIFACT_REGISTRY: ${{ inputs.google_artifact_registry }}
      IMAGE_NAME:  ${{ inputs.image_name }}
      IMAGE_TAG: ${{ inputs.image_tag }}
      CLOUD_RUN_SERVICE_ACCOUNT: ${{ inputs.cloud_run_service_account }}
      MAX_INSTANCES: ${{ inputs.max_instances }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        submodules: recursive

    - id: 'auth'
      uses: 'google-github-actions/auth@v2.0.1'
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.workload_identity_service_account }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2.0.1'

    - id: auth_docker
      name: "Auth Docker"
      run: |-
        gcloud auth configure-docker us-docker.pkg.dev

    - id: build_image
      name: 'Build Docker image to GAR'
      run: "gcloud builds submit --tag us-docker.pkg.dev/$GCLOUD_PROJECT/$GOOGLE_ARTIFACT_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"

    - id: generate_sbom
      name: 'Generate SBOM for Image'
      run: "gcloud artifacts sbom export --uri=us-docker.pkg.dev/$GCLOUD_PROJECT/$GOOGLE_ARTIFACT_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"

    - id: retag_image_as_latest
      name: 'Tag image as latest'
      run: |-
        docker pull us-docker.pkg.dev/$GCLOUD_PROJECT/$GOOGLE_ARTIFACT_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        docker tag us-docker.pkg.dev/$GCLOUD_PROJECT/$GOOGLE_ARTIFACT_REGISTRY/$IMAGE_NAME:$IMAGE_TAG us-docker.pkg.dev/$GCLOUD_PROJECT/$GOOGLE_ARTIFACT_REGISTRY/$IMAGE_NAME:latest
        docker push us-docker.pkg.dev/$GCLOUD_PROJECT/$GOOGLE_ARTIFACT_REGISTRY/$IMAGE_NAME:latest

    - id: deploy_image
      name: "Deploy image to Cloud Run"
      run: "gcloud run deploy --image=us-docker.pkg.dev/$GCLOUD_PROJECT/$GOOGLE_ARTIFACT_REGISTRY/$IMAGE_NAME:$IMAGE_TAG --allow-unauthenticated --max-instances $MAX_INSTANCES --platform managed --region=$GOOGLE_REGION $IMAGE_NAME --service-account=$CLOUD_RUN_SERVICE_ACCOUNT"
