name: Make a new Release

on:
  workflow_call:
    inputs:
      relative_package_file_path:
        description: 'Package file (like package.json, Cargo.toml, etc) that needs to be updated'
        required: false
        type: string
      version_prefix:
        description: 'String to prefix releases with'
        default: 'v'
        required: false
        type: string
      default_increment:
        description: 'Default release version, one of major, minor, patch'
        default: 'minor'
        required: false
        type: string
    secrets:
      input_github_token:
        required: true
    outputs:
      version:
        description: "The release tag created"
        value: ${{ jobs.make-new-release.outputs.version }}

jobs:
  make-new-release:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      pull-requests: 'read'
      id-token: 'write'
    env:
      GITHUB_TOKEN: ${{ secrets.input_github_token }}
    outputs:
      version: ${{ steps.bump_release.outputs.version }}

    steps:
    - id: bump_release
      name: Bump Release
      uses: rymndhng/release-on-push-action@v0.28.0
      with:
        bump_version_scheme: ${{ github.actor == 'dependabot[bot]' && 'patch' || inputs.default_increment  }}
        dry_run: false
        tag_prefix: ${{ inputs.version_prefix }}

  update-package-file:
    runs-on: ubuntu-latest
    if: ${{ inputs.relative_package_file_path == 'Cargo.toml'}}
    permissions:
      contents: 'write'
      pull-requests: 'read'
      id-token: 'write'
    env:
      GITHUB_TOKEN: ${{ secrets.input_github_token }}
    needs: [ make-new-release ]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4.2.1
    - name: "Update Cargo.toml"
      run: |
        sed -i.bak -e 's/^\s*version = "\{0,1\}[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*"\s*$/version = "${{ needs.make-new-release.outputs.version }}"/g' Cargo.toml
    - name: Commit and push changes
      run: |
        git config --global user.name "pcarton"
        git config --global user.email "patrick.d.carton@gmail.com"
        git config advice.addIgnoredFile false
        git add Cargo.toml
        git commit -m "Update Cargo.toml"
        git push
