name: version the actions

on:
  push:
    branches:
      - main

jobs:
  make-new-release:
    uses: pcarton/github-actions/.github/workflows/make-release.yaml@v0.4.0
    secrets:
      input_github_token: ${{ secrets.GITHUB_TOKEN }}
