name: version the actions

on:
  push:
    branches:
      - main
      - version-step

jobs:
  make-new-release:
    uses: pcarton/github-actions/.github/workflows/make-release@version-step
    secrets:
      input_github_token: ${{ secrets.GITHUB_TOKEN }}
